# Generated by Django on 2026-09-01
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='👕', help_text='Emoji or icon for category bubble', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_type',
            field=models.CharField(choices=[('Oversized Drop Shoulder', 'Oversized Drop Shoulder'), ('Boxy Streetwear Fit', 'Boxy Streetwear Fit'), ('Relaxed Fit', 'Relaxed Fit'), ('Classic Regular Fit', 'Classic Regular Fit')], default='Oversized Drop Shoulder', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gsm',
            field=models.PositiveIntegerField(default=240, help_text='Fabric weight in GSM (e.g. 240, 260, 280)'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_type',
            field=models.CharField(choices=[('High-Density Puff Print', 'High-Density Puff Print'), ('Ultra-HD DTG Print', 'Ultra-HD Direct-to-Garment (DTG)'), ('Vintage Distressed Screen Print', 'Vintage Distressed Screen Print'), ('Reflective Neon Holographic', 'Reflective Neon Holographic'), ('Silicone Rubberized Suede Print', 'Silicone Rubberized Suede Print'), ('Metallic Foil Screen Print', 'Metallic Foil Screen Print')], default='High-Density Puff Print', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='awb_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, help_text='e.g. Front View, Back Print, Model Shot, Detail', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
