# Generated by Django 5.2.17 on 2026-08-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_order_discount_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
