# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_icon_and_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
