# Generated by Django 5.2.17 on 2026-09-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_phone_number_and_product_variant'),
        ('store', '0005_order_phone_number_productvariant'),
    ]

    operations = [
    ]
