# Generated by Django 5.2.17 on 2026-09-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_icon_and_features'),
        ('store', '0007_remove_order_tracking_number_category_icon_and_more'),
    ]

    operations = [
    ]
